// Fallback for when browsers block fetching local files (file://).
// Generated by hand from conversations.txt so the page works when opened directly.
window.CONVERSATIONS_TEXT = `## Rawls vs Nozick conversation data
## Format:
## @prompt: <prompt text>
## R: <Rawls line>
## N: <Nozick line>
## (repeat R:/N: as needed)

@prompt: Should the government provide universal healthcare funded by taxes?
R: In a society designed behind a veil of ignorance, we would endorse institutions that secure fair equality of opportunity. Preventable illness undermines that opportunity, so basic healthcare fits within what we would reasonably guarantee to all.
N: Tax funding turns some people into means for others, compelling them to labor for strangers. Voluntary charity and mutual aid are permissible; coercive redistribution violates individual rights.
R: The question is not charity but the terms of social cooperation among free and equal citizens. If inequalities are allowed only when they benefit the least advantaged, then broad access to care can be justified as part of a fair basic structure.
N: A “basic structure” cannot override side constraints. Even if an outcome is attractive, it does not follow that others may be forced to provide it.
R: We can respect persons as ends by ensuring the background conditions that make choice meaningful. Health shocks are morally arbitrary; just institutions neutralize such contingencies.
N: Neutralizing contingencies by mandate is still a taking. The moral arbitrariness of luck does not create a claim on other people’s holdings.

@prompt: Is it justifiable to ban certain books from public schools?
R: Public education should cultivate citizens’ capacities for moral powers while respecting reasonable pluralism. A ban is justified only if the material directly undermines those civic aims in a way that cannot be addressed by context, discussion, and age-appropriate framing.
N: Bans are an abuse of state monopoly schooling. If parents want restrictions, they can choose schools accordingly; the state should not dictate what peaceful ideas may be accessed.
R: Yet public institutions must be justifiable to each citizen. If certain content predictably targets or degrades a subset of students, it may violate the fair value of equal political liberties by marginalizing them.
N: The cure is exit and competition, not centralized control. Censoring books imposes one group’s preferences on others.
R: I’m not defending preference; I’m defending the equal standing required for a well-ordered society. The default should be inclusion with deliberation, not suppression.
N: And the default should be freedom with choice, not bureaucratic paternalism.

@prompt: Should colleges use affirmative action in admissions?
R: If social and economic inequalities distort life chances, fair equality of opportunity is not satisfied. Carefully designed policies can correct for unjust background conditions and make the competition for positions genuinely fair.
N: Admissions are the property of the institution and the applicants’ achievements. Using race or group identity as a lever treats individuals as tokens and violates equal respect.
R: Individuals are not responsible for the social starting points that shape their achievements. A just system adjusts institutions so that arbitrary contingencies do not determine prospects.
N: Adjusting by overriding individual merit is itself an injustice. It replaces one unfairness with another and infringes on freedom of association.
R: Merit is not morally pure when its production depends on inherited advantage. The difference principle permits arrangements that improve the position of those worst off overall.
N: The principle still cannot authorize violating rights. No end-state pattern justifies forced departures from voluntary choices.

@prompt: Is mass surveillance justified to reduce crime?
R: Basic liberties have priority; privacy supports freedom of thought and association. Surveillance must be narrowly tailored, publicly justifiable, and constrained by rule of law to avoid turning citizens into subjects.
N: Surveillance is a presumptively illegitimate invasion. Treating everyone as a suspect violates side constraints and chills the free exercise of rights.
R: Some security measures may be permissible if they are part of a scheme that all could accept under conditions of fairness, including strong oversight and equal application.
N: Oversight does not transform coercion into consent. If the state can watch everyone, it accumulates power that will be abused.
R: That is why institutions must be designed to prevent domination. Still, the mere possibility of abuse is not a decisive argument against any data collection.
N: The burden is on the state to justify intrusion; historically it fails. Freedom requires leaving peaceful people alone.

@prompt: Should social media platforms be required to moderate misinformation?
R: The fair value of political liberties depends on citizens having access to reliable information. If platforms function as quasi-public forums, moderate requirements could be justified to protect democratic deliberation, provided they are transparent and appealable.
N: Mandated moderation is compelled speech by proxy. Private platforms should set their own rules, and users should be free to choose among them without state direction.
R: If concentrated market power makes “choice” illusory, regulation can be part of ensuring fair terms of cooperation. But it must not become a tool for partisan control.
N: Once the state sets the boundary of “misinformation,” it will expand it. The remedy for bad speech is more speech, not forced curation.
R: More speech works only when the informational environment isn’t systematically polluted. Civic trust is a public good.
N: Public goods rhetoric is the classic path to restricting liberty.

@prompt: Is it ethical to require organ donation at death (opt-out or mandated)?
R: Under the veil of ignorance, many would endorse an opt-out default: it saves lives with minimal burden while respecting conscientious refusal. A mandate is harder to justify because bodily integrity and self-ownership concerns are weighty.
N: Even at death, a person’s body is not the state’s resource. Opt-out systems are manipulative; mandated donation is outright theft.
R: Defaults can be justified if they are transparent and easy to refuse. The aim is to align institutions with what reasonable people would accept as fair.
N: “Reasonable people” is not a license to seize. Rights do not dissolve for social convenience.
R: Still, the social basis of self-respect includes knowing that institutions do not allow avoidable deaths due to coordination failures.
N: Coordination failures do not create claims over other people’s bodies.

@prompt: Should minimum wage laws be increased significantly?
R: If labor markets yield outcomes that leave full-time workers unable to participate as equals, then the basic structure is failing. A wage floor can be justified if it improves the position of the least advantaged without undermining opportunity.
N: Wage floors restrict freedom of contract and harm the very people they claim to help by pricing them out. Voluntary exchange should set wages.
R: Voluntary exchange occurs within background conditions shaped by law and power. A fair system sets limits so that bargaining does not become exploitation.
N: “Exploitation” here is just dislike of outcomes. If both parties consent, outsiders have no right to interfere.
R: Consent under desperation is morally compromised when institutions permit such desperation. Justice addresses that.
N: Justice does not mean engineering outcomes; it means respecting rights.

@prompt: Is it justifiable to require vaccines for school attendance?
R: Public health measures can be consistent with equal liberty when they protect the basic conditions for everyone’s freedom, especially the vulnerable. Exemptions should exist for genuine medical contraindications, and policy should be proportionate and publicly reasoned.
N: Conditioning school access on medical procedures coerces families. If a school is public, it should not impose such requirements; if private, it may, but the state should not mandate.
R: A shared school system is part of fair opportunity. Preventing outbreaks protects that system and the least advantaged who suffer most from disease.
N: Again, ends do not justify means. Individuals own their bodies; risk imposition is not a blank check for compulsion.
R: Yet refusing vaccination can impose significant risks on others who cannot consent or protect themselves. Liberty is bounded by the equal liberty of all.
N: Treating unvaccinated people as rights violators is a slippery expansion of state power.

@prompt: Should landlords be allowed to raise rent without limit during shortages?
R: Housing is tightly connected to opportunity and the social bases of self-respect. Unbounded rent increases during shortages can make equality of opportunity hollow; regulation may be justified to protect the least advantaged.
N: Price controls violate property rights and worsen shortages. Landlords are entitled to set terms for use of their property; higher prices signal scarcity and attract supply.
R: Scarcity signals do not excuse outcomes that systematically exclude citizens from basic participation. Institutions can combine supply incentives with protections against displacement.
N: Combining incentives with coercion still violates rights. If the state wants housing, it can build it without interfering in private contracts.
R: Public provision is one route; regulation is another. The question is which arrangement people would choose not knowing their position.
N: Ignorance is not a moral argument for overriding ownership.

@prompt: Is it justifiable to criminalize certain recreational drugs?
R: Criminalization can undermine fair equality of opportunity by creating cycles of exclusion. If harms are primarily to the user, a just society leans toward regulation and public health rather than punishment, especially given unequal enforcement.
N: Adults should be free to take risks with their own bodies. Criminalization is paternalism and an overreach; it also fuels black markets because the state interferes.
R: Still, some drugs create externalities that harm families and communities, including children. Policy must protect the vulnerable without turning social problems into carceral ones.
N: Externalities can be addressed with targeted liability, not blanket prohibitions. Prohibition is collective punishment.
R: Liability assumes resources and access to justice that the least advantaged often lack. Institutions should be designed to protect them in practice.
N: Designing institutions doesn’t justify banning peaceful behavior.

@prompt: Should governments guarantee a basic income for all citizens?
R: A basic income can support the social minimum needed for citizens to exercise their moral powers and participate as equals. If it strengthens the position of the least advantaged and preserves fair opportunity, it fits within a just basic structure.
N: Basic income is redistribution by force. It requires taking from some to give to others; it violates self-ownership and the entitlement theory of justice.
R: Entitlement depends on the background rules that define property and contracts. Those rules must be chosen fairly; otherwise “entitlement” simply reflects historical luck and power.
N: The history matters because transfers must be voluntary. You cannot fix past injustice by committing new injustice.
R: A stable society requires that citizens see institutions as fair. A social minimum is part of that public justification.
N: Stability is not a moral permission slip to violate rights.
`;

